file_html = open("respuestap1.html", "w")
# Adding the input data to the HTML file
file_html.write("<!DOCTYPE html>")
file_html.write("<html>")
file_html.write("<head>")
file_html.write("  <script>")
file_html.write("  function openLink() {")
file_html.write("    document.getElementById(\"p2\").innerHTML = \"<table border=1px><tr><td>sebastian</td><td>rojo</td></tr></table>\";")
file_html.write("    document.getElementById(\"p3\").innerHTML = \"<table border=1px><tr><td>roberto</td><td>verde</td></tr></table>\";")
file_html.write("    document.getElementById(\"p4\").innerHTML = \"<table border=1px><tr><td>carla</td><td>azul</td></tr></table>\";")
file_html.write("}")
file_html.write("  </script>")
file_html.write("</head>")
file_html.write("<body>")
file_html.write("<h1>Resultados - pregunta 1</h1>")
file_html.write("<button type=\"button\" onclick=\"openLink()\">Resultados</button>")
file_html.write("<p id=\"p2\"></p>")
file_html.write("<p id=\"p3\"></p>")
file_html.write("<p id=\"p4\"></p>")
file_html.write("</body>")
file_html.write("</html>")
# Saving the data into the HTML file
file_html.close()
